name: CI/CD Pieline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    
    - name: build image
      run : |
        docker build -t manjunadh965/expense:${{ github.sha }} .
      

    - name: docker login 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: push image
      run : docker push manjunadh965/expense:${{ github.sha }}

    - name: deployment in ec2
      run: |
        curl -o $(pwd)/testing.pem ${{ secrets.TEST_URL }}
        ssh -o StrictHostKeyChecking=no -i testing.pem ubuntu@${{ secrets.EC2_HOST}} << 'EOF'
          sudo docker pull manjunadh965/expense:${{ github.sha }}
          sudo docker stop service || true
          sudo docker rm service || true
          sudo docker run -d --env-file .env --name service -p 8600:8600 manjunadh965/expense
        EOF
    
    - name: cleaning files
      run: rm -f testing.pem
    
    # - name: post msg in ms teams
    #   uses: opsless/ms-teams-github-actions@main
    #   if: always() # to let this step always run even if previous step failed
    #   with:
    #     github-token: ${{ github.token }}
    #     webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
