name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
          expr 101 + 199 > math.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: |
            math-homework.txt
            math.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        # with:
        #   name: homework_pre
        #   path: .
      - shell: bash
        run: |
          ls homework_pre
          cd homework_pre
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
          value2='cat math.txt'
          expr $value2 \* 99 > math.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v4
        with:
          name: homework_final
          path: |
            math-homework.txt
            math.txt
            
  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v4
        # with:
        #   name: homework_final
        #   path: .
      - name: Print the final result
        shell: bash
        run: |
          cd homework_final
          value=`cat math-homework.txt`
          echo The result is $value
          value2='cat math.txt'
          echo the result is $value2
          
